name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set up timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Europe/Madrid

    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Compile LaTeX document
      run: |
        apt update && apt upgrade -y
        apt install texlive-full latexmk -y
        latexmk -xelatex document.pdf

    - name: Get version name
      id: version
      run: echo "::set-output name=version::$(echo -e $(date +'%Y-%m-%d.%H%M%S.')$(echo -e ${GITHUB_SHA} | cut -c1-16))"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v.${{ steps.version.outputs.version }}
        release_name: Release v.${{ steps.version.outputs.version }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_path: ./document.pdf
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: document-v.${{ steps.version.outputs.version }}.pdf
        asset_content_type: application/pdf

    - name: Rename file
      run: mv ./document.pdf ./document-v.${{ steps.version.outputs.version }}.pdf

    - name: Send file to Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: 🔖 New version of document with name `document-v.${{ steps.version.outputs.version }}.pdf` 🔖
        format: markdown
        document: ./document-v.${{ steps.version.outputs.version }}.pdf
