name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set up timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Europe/Madrid

    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: document.tex
        extra_system_packages: "py-pygments"
        latexmk_use_xelatex: true
        latexmk_shell_escape: true

    - name: Set version name
      id: version
      run: |
        DATE=$(date +'%Y%m%d%H%M%S')
        HASH=$(echo -e ${GITHUB_SHA} | cut -c1-8)
        EVENT=${GITHUB_EVENT_NAME}
        if [ "$EVENT" = "pull_request" ]; then
            BRANCH=${GITHUB_HEAD_REF}
        else
            BRANCH=${GITHUB_REF##*/}
        fi
        if [ "$BRANCH" = "master" ]; then
            VERSION="$DATE.$HASH"
        else
            VERSION="$DATE.$HASH.$BRANCH"
        fi
        echo "Version: $VERSION"
        echo "::set-output name=version::$(echo v.$VERSION)"

    - run: |
        set -x
        assets=()
        for asset in ./*.pdf report.txt; do
          assets+=("-a" "$asset")
        done
        hub release create "${assets[@]}" -m "${{ steps.version.outputs.version }}" "${{ steps.version.outputs.version }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create different versions
      run: bash create-versions.sh ./document.pdf


    - name: Rename file
      run: mv ./document.pdf ./document-${{ steps.version.outputs.version }}.pdf

    - name: Send file to Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: 🔖 New version of document with name `document-${{ steps.version.outputs.version }}.pdf` 🔖
        format: markdown
        document: ./document-${{ steps.version.outputs.version }}.pdf
